class CreateAuthentications < ActiveRecord::Migration[5.2]
  def change
    create_table :authentications do |t|
      t.string :uid #Generated by the provider to uniquely identify them!
      t.string :token #an access token - allows you to access information / actions from the provider. For example, 'post on twitter'
      t.string :provider #the actual provider of the info/auth. Eg google, facebook.
      t.references :user, foreign_key: true # id of the user to be stores in our database

      t.timestamps
    end
  end
end
